import Head from 'next/head'
import Connect from '../metamask/Connect'
import Deeplink from '../metamask/Deeplink'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Connect Metamask</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Connect/>
        <Deeplink/>
        <div id='display' ></div>
      </div>
    </>
  )
}
